project:
  type: website
  output-dir: docs

website:
  title: "jhp"
  navbar:
    left:
      - href: about.qmd
        text: About
      - posts.qmd
      - projects.qmd
    right:
    - icon: github
      href: https://github.com/jhp1630
    - icon: envelope
      href: mailto:jhp1630@gmail.com
  cookie-consent: true
  
  search: 
    location: navbar
  page-footer:
    background: light
    left: © jhp 2025
    right: Website built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    page-layout: full
    smooth-scroll: true